### ISSUE TITLE
meta tags for social media

### ISSUE THREAD

**Issue by codemonkey-uk** [codemonkey-uk/gawm#109]
Following advice from:
https://css-tricks.com/essential-meta-tags-social-media/

Checking with tools:
https://developers.facebook.com/tools/debug/?q=gawm.link
https://cards-dev.twitter.com/validator

Tasks:
- [x] Create placeholder image
- [x] Add meta tags
- [x] Check against tools
- [x] Make final preview image @JiFish 

WIP in git branch metatags / ecf2e1f
